_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 16
                - 23
                - 55
                - 62
            "4": 3.12.8
            "5": 0.19.8
            "8":
                - 1
                - 5
            "12": 0.19.8
            "13": darwin-arm64
batch_size:
    value: 32
d_ff:
    value: 64
d_model:
    value: 32
dropout:
    value: 0.1
learning_rate:
    value: 0.0001
n_heads:
    value: 4
num_decoder_layers:
    value: 6
num_encoder_layers:
    value: 6
num_epochs:
    value: 50
src_vocab_size:
    value: 100
tgt_vocab_size:
    value: 200
