wandb_version: 1

batch_size:
  desc: null
  value: 32
epochs:
  desc: null
  value: 100
learning_rate:
  desc: null
  value: 0.001
window_size:
  desc: null
  value: 3
max_vocab_size:
  desc: null
  value: 50
_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.15.12
    framework: huggingface
    huggingface_version: 4.33.3
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1743398075.841949
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.10.16
      5: 0.15.12
      6: 4.33.3
      8:
      - 1
      - 5
      13: darwin-arm64
